### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by fridaystreet** [destinydriven/cakephp-highcharts#14]
Hi,

I tried installing from the instructions via git, but the charts don't load. When I view the console in chrome it shows it can't find highchart.js and other css files. I have a fully working cakephp application running in this app, I'm just trying to add some graphing capabilities to it.

see screenshot here 
http://screencast.com/t/Nph8yA09PNmX

Cheers
Paul

**Comment by destinydriven** [comment]
Closing as this issue appears to be specific to you.
