### ISSUE TITLE
Uncaught TypeError: N is not a function

### ISSUE THREAD

**Issue by MarcoDias7** [destinydriven/cakephp-highcharts#28]
Hi,

I followed every step of the tutorial, but when I want to display the chart, I have this error in the console.

I seem to have JQuery already working in the project, so I really don't know.

If you could help me, that would be very kind.

**Comment by destinydriven** [comment]
Can you show me all the code you used to try to generate your chart?                                                                                                                                                                                                                                                                                                                                        With the spoon of determination in the hand of faith you can carve a tunnel of hope through the mountain of despair.                                                                                                                                                                                                                 From: MarcoDias7Sent: Monday, April 20, 2015 7:37 PMTo: destinydriven/cakephp-highcharts-pluginReply To: destinydriven/cakephp-highcharts-pluginSubject: [cakephp-highcharts-plugin] Uncaught TypeError: N is not a function (#28)Hi,

I followed every step of the tutorial, but when I want to display the chart, I have this error in the console.

I seem to have JQuery already working in the project, so I really don't know.

—Reply to this email directly or view it on GitHub.

**Comment by MarcoDias7** [comment]
This is an example I found, I wanted to try it before doing my own chart :

$chartData = array(
				array(
						'name' => 'Chrome',
						'y' => 45.0,
						'sliced' => true,
						'selected' => true
				),
				array('IE', 26.8),
				array('Firefox', 12.8),
				array('Safari', 8.5),
				array('Opera', 6.2),
				array('Others', 0.7)
		);
		$chartName = 'Pie Chart';
		$pieChart = $this->Highcharts->create( $chartName, 'pie' );
		$this->Highcharts->setChartParams(
				$chartName,
				array
				(
						'renderTo'  => 'piewrapper',  // div to display chart inside
						'chartWidth' => 1000,
						'chartHeight' => 750,
						'chartTheme' => 'gray',
						'title'  => 'Browser Usage Statistics',
						'plotOptionsShowInLegend' => TRUE,
						'creditsEnabled'  => FALSE
				)
		);
		$series = $this->Highcharts->addChartSeries();
		$series->addName('Browser Share')
		->addData($chartData);
		$pieChart->addSeries($series);

I'm using this on top :

public $components = array (
			'Paginator',
			'Session',
			'Highcharts.Highcharts'
	);

And in the view : 

<div id="piewrapper" style="display: block; float: left; width:90%; margin-bottom: 20px;"></div>

<?php echo $this->Highcharts->render('Pie Chart'); ?>

He seems to find my chart, since if I modify the value in render(), I have an error, it just doesn't display.

**Comment by destinydriven** [comment]
Are you passing  $chartName to your view?  You code is missing the line:
        $this->set(compact('chartName'));

And use this in your view:
       <?php echo $this->Highcharts->render($chartName); ?>

That should work for you.
