### ISSUE TITLE
Export issue 

### ISSUE THREAD

**Issue by sf84** [destinydriven/cakephp-highcharts#31]
exporting.js is not include if one of charts in the page has "exportingEnabled" to false. All charts need to have "exportingEnabled" to true to load exporting.js

**Comment by destinydriven** [comment]
@sf84 exporting.js is being loaded on the page through the helper (https://github.com/destinydriven/cakephp-highcharts-plugin/blob/master/View/Helper/HighchartsHelper.php#L45).  I suppose we can load this file on every page by default so we can deal with each chart's settings separately.  What do you think?

**Comment by destinydriven** [comment]
Closing this issue since it has been resolved in the last commit https://github.com/destinydriven/cakephp-highcharts/commit/a4e7e9f5049665974253f99388432a00368d0f08 .  Feel free to reopen this issue if it doesn't adequately address your problem.
